name: Build Cantor Keyboard Firmware

on:
  push:
    branches:
      - build  # Change this to the appropriate branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QMK environment
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip dfu-util
        pip3 install qmk

    - name: Clone QMK firmware
      run: |
        git clone https://github.com/qmk/qmk_firmware.git
        cd qmk_firmware
        git submodule update --init --recursive

    - name: Compile firmware
      run: |
        cd qmk_firmware
        qmk compile -kb cantor -km default  # Adjust layout if needed

    # You can add additional steps here, such as uploading firmware, etc.
